# Generated by Django 4.0.3 on 2022-03-07 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_acntexpensest_course_user_registration_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlist',
            name='course',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total', to='base_app.course'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_name', to='base_app.course'),
        ),
    ]
