# Generated by Django 4.0.3 on 2022-03-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_acntspayslip_basictype_acntspayslip_contype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='total_pay',
            field=models.IntegerField(default='0'),
        ),
    ]
