# Generated by Django 4.0.3 on 2022-03-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_user_registration_total_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='payment_balance',
            field=models.IntegerField(default='0'),
        ),
    ]
